In [6]:
import numpy as np
import cv2
from collections import Counter
from collections import OrderedDict
from scipy import stats
import operator

In [30]:
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])
x = np.array([[1,2,3],[1,0,0]])
y = np.array([[1,2,3],[1,2,3]])

array([False, False, False, False])

In [33]:
arr = np.arange(6).reshape(2, 3)
arr    

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
np.add(z,a)

array([[1., 2., 3.],
       [1., 0., 0.]])

In [2]:
list = [1,2,3,4,1,2,6,7,3,8,1] 
cnt = Counter(list)  

In [4]:
cnt

Counter({1: 3, 2: 2, 3: 2, 4: 1, 6: 1, 7: 1, 8: 1})

In [2]:
cnt.items()

NameError: name 'cnt' is not defined

In [92]:
imax = 1
for key,val in cnt.items():
    if(cnt.get(imax))
    print(key,"= ",val)

1 =  3
2 =  2
3 =  2
4 =  1
6 =  1
7 =  1
8 =  1


In [94]:
cnt.get(imax)

3

In [85]:
max[1] = max[2]

In [86]:
max

{1: 10, 2: 10}

In [95]:
imgpath = "D:/imageproc/lvl3.jpg"
img = cv2.imread(imgpath)
b, g, r = cv2.split(img)

In [205]:
bcn = Counter(b.ravel())
lbcn = sorted(bcn.items())

In [253]:
b

array([[131, 124, 112, ..., 130, 133, 135],
       [130, 122, 111, ..., 131, 135, 137],
       [132, 124, 113, ..., 131, 135, 138],
       ...,
       [101, 100, 100, ..., 119, 120, 120],
       [101, 102, 102, ..., 119, 120, 120],
       [104, 104, 104, ..., 119, 120, 120]], dtype=uint8)

In [276]:
def getModus(image):
    imgdic = Counter(image.ravel())
    imgarr = sorted(imgdic.items())
    nilai = 0
    for i in range(len(imgarr)):
        key,value = imgarr[i]
        if(i==0):
            modus = key
        else:
            if(value > imgdic.get(modus)):
                modus = key
    return modus


def drawImage(b,g,r):
    a = np.zeros(2)
    result = np.array([b,g,r])
    baris = np.array([b,g,r])
    result = np.array([result])
    for i in range(0,1250):
        baris = np.insert(result,1,baris,axis = 0)
        
    result = np.array([baris])
    
    for i in range(0,1250):
        result = np.insert(result,1,baris, axis = 0)
        
    print(img.shape)
    cv2.imshow('image',result)
    cv2.waitKey(0)
    cv2.destroyAllWindows() 

In [277]:
mb = getModus(b)
mg = getModus(g)
mr = getModus(r)

In [278]:
drawImage(mb,mg,mr)

(283, 212, 3)


In [240]:
tup

(1, 2, 3)

In [261]:
    a = np.zeros(2)
    result = np.insert(a,2,255)

In [268]:
a = None

In [269]:
np.insert(a,0,244)

array([244, None], dtype=object)