In [28]:
import cv2
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
import pandas as pd
import math

def showImage(data):
    if(type(data) is list):
        for i in range(len(data)):
            cv2.imshow('Gambar'+str(i+1),data[i])
    elif((type(data).__module__) == "numpy"):
        cv2.imshow('Gambar',data)
    else:
        print('File Error')
    
    cv2.waitKey(0)
    cv2.destroyAllWindows() 

In [56]:
# path = "D:\imageproc\Level 2\lv2-4.jpg"
# path = "D:\imageproc\Level 3\lv3-8.jpg"
path = "D:\imageproc\Level 4\lv4-8.jpg"
# path = "D:\imageproc\Random\out3.jpg"

img = cv2.imread(path,1)
img = cv2.resize(img,None,fx=0.3,fy=0.3)


In [59]:
showImage([img,img+200])

In [61]:
img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
img.shape

(332, 443, 3)

In [63]:
keep_mask = x==50
out = np.where(x>50,0,1)
out[keep_mask] = 50

NameError: name 'x' is not defined

In [94]:
# np.where(img <= 255,img, 255)
img+31

array([[[255, 250, 247],
        [255, 250, 247],
        [  1, 252, 249],
        ...,
        [239, 234, 231],
        [241, 236, 233],
        [239, 238, 234]],

       [[  1, 252, 249],
        [  1, 252, 249],
        [  1, 252, 249],
        ...,
        [239, 234, 231],
        [241, 236, 233],
        [239, 238, 234]],

       [[  2, 253, 250],
        [  2, 253, 250],
        [  1, 252, 249],
        ...,
        [241, 236, 233],
        [241, 237, 234],
        [239, 238, 234]],

       ...,

       [[249, 240, 237],
        [249, 240, 237],
        [247, 238, 235],
        ...,
        [176, 168, 168],
        [177, 169, 169],
        [174, 166, 166]],

       [[249, 240, 237],
        [249, 240, 237],
        [249, 240, 237],
        ...,
        [176, 168, 168],
        [177, 169, 169],
        [174, 166, 166]],

       [[250, 241, 238],
        [249, 240, 237],
        [247, 238, 235],
        ...,
        [175, 167, 167],
        [174, 166, 166],
        [177, 167, 167]]

img

In [204]:
img6 = img6 = img.astype('uint16')

In [205]:
img6 = img6 + 200 

In [206]:
img6 = np.where(img6 <= 255,img6,255)

In [207]:
img6


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [228]:
hsvimg = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

In [210]:
maxseg = np.array([[[100,255,255]]],dtype="uint8")
minseg = np.array([[[34,100,10]]],dtype="uint8")

In [218]:
cv2.cvtColor(maxseg, cv2.COLOR_HSV2BGR)

array([[[255, 170,   0]]], dtype=uint8)

In [219]:
cv2.cvtColor(minseg, cv2.COLOR_BGR2RGB)

array([[[ 10, 100,  34]]], dtype=uint8)

In [254]:
maxg = (100, 255,   255)
ming = ( 34, 100,  10)

In [255]:
mask = cv2.inRange(hsvimg,ming,maxg)

In [256]:
result = cv2.bitwise_and(img, img, mask=mask)

In [257]:
showImage(result)

SyntaxError: invalid syntax (<ipython-input-258-30a26617a575>, line 1)

In [259]:
a

array([1, 2, 3, 4])