In [44]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats
from collections import Counter 

def showImage(data):
    if(type(data) is list):
        for i in range(len(data)):
            cv2.imshow('Gambar'+str(i+1),data[i])
    elif((type(data).__module__) == "numpy"):
        cv2.imshow('Gambar',data)
    else:
        print('File Error')
    
    cv2.waitKey(0)
    cv2.destroyAllWindows() 

def gsAverage(img):
    (M, N, C) = img.shape
    grayImage = np.zeros([M,N])
    for m in range(M):
        for n in range(N):
            B = int(img[m,n,0]) 
            G = int(img[m,n,1])
            R = int(img[m,n,2])           
            grayImage[m,n] = round((R+G+B)/3,0)
    return grayImage.astype('uint8')


def bi(img):
    img = gsAverage(img)
    (M, N) = img.shape
    newImage = np.zeros([M,N])
    T = 127
    for m in range(M):
        for n in range(N):
            if(img[m,n] <= T):
                newImage[m,n] = 0
            else:
                newImage[m,n] = 255
    return newImage.astype('uint8')


def colorHistogram(img):
    b, g, r = cv2.split(img)
    # cv2.imshow("b", b)
    # cv2.imshow("g", g)
    # cv2.imshow("r", r)
    plt.hist(b.ravel(), 256, [0, 256])
    plt.hist(g.ravel(), 256, [0, 256])
    plt.hist(r.ravel(), 256, [0, 256])
    plt.show()

def getModus(image):
    imgdic = Counter(image.ravel())
    imgarr = sorted(imgdic.items())
    nilai = 0
    for i in range(len(imgarr)):
        key,value = imgarr[i]
        if(i==0):
            modus = key
        else:
            if(value > imgdic.get(modus)):
                modus = key
    return modus

# def rgb_to_hsv(img):
#     (M, N, C) = img.shape
#     newImage = np.zeros([M,N,C])
#     for m in range(M):
#         for n in range(N):
#             B = float(img[m,n,0]) 
#             G = float(img[m,n,1])
#             R = float(img[m,n,2])
            
#             b = B/(R+G+B)
#             g = G/(R+G+B)
#             r = R/(R+G+B)
            
#             V = max(r,g,b)
            
#             if(V==0):
#                 S = 0
#             else:
#                 S = 1 - (min(r,g,b)/V)
                
#             if(S==0):
#                 H = 0
#             elif(V==r):
#                 H = (60*(g-b))/(S*V)
#             elif(V==g):
#                 H = 60*(2+(b-r)/(S*V))
#             elif(V==b):
#                 H = 60*(4+(r-g)/(S*V))
            
#             if(H < 0):
#                 H = H + 360
                
#             newImage[m,n,0] = H 
#             newImage[m,n,1] = S
#             newImage[m,n,2] = V
#     return newImage


def rgb_to_hsv(img):  
    (M, N, C) = img.shape
    newImage = np.zeros([M,N,C])
    for m in range(M):
        for n in range(N):
            B = float(img[m,n,0]) 
            G = float(img[m,n,1])
            R = float(img[m,n,2])

            V = max(R,G,B)

            Vm = V-min(R,G,B)

            if(V == 0):
                S = 0
            elif(V > 0):
                S = Vm/V

            if(S == 0):
                H = 0
            elif(V == R):
                H = (60/360)*(((G-B)/Vm)%6)
            elif(V == G):
                H = (60/360)*(2+((B-R)/Vm))
            elif(V == B):
                H = (60/360)*(4+((R-G)/Vm))

          

            newImage[m,n,0] = H 
            newImage[m,n,1] = S
            newImage[m,n,2] = V
    return newImage

def customImg(image):
    (M, N, C) = image.shape
    for m in range(M):
        for n in range(N):        
            image[m,n,1] = 0
            image[m,n,2] = 0
    return image.astype('uint8')


def segmentation(img):
    (M, N, C) = img.shape
    newImage = np.zeros([M,N])
    for m in range(M):
        for n in range(N):
            h = img[m,n,0]
            s = img[m,n,1]
            if((h <= 109) and(h >= 30)):
                newImage[m,n] = 0
            else:
                newImage[m,n] = 255
    return newImage.astype('uint8')

In [47]:
imgpath = "D:/imageproc/lv2.jpg"
img = cv2.imread(imgpath)
img = cv2.resize(img,None,fx=0.2,fy=0.2)
hsv = rgb_to_hsv(img)
h,s,v = cv2.split(hsvimg)
showImage([img,hsv,h,s,v])


In [28]:
imgpath = "D:/imageproc/lv2.jpg"
img = cv2.imread(imgpath)
img = cv2.resize(img,None,fx=0.2,fy=0.2)
hsv = rgb_to_hsv(img)
hsvimg = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
rgbimg = cv2.cvtColor(hsvimg, cv2.COLOR_HSV2BGR)
h,s,v = cv2.split(hsvimg)
b,g,r = cv2.split(rgbimg)
hr = h.ravel()
sr = s.ravel()
vr = v.ravel()

hsv.ravel()



array([5.45454545e-01, 5.21327014e-02, 2.11000000e+02, ...,
       5.25641026e-01, 5.55555556e-02, 2.34000000e+02])

In [32]:
showImage(v)

In [140]:
hsvimg[:,:,0]

array([[109, 109, 109, ..., 113, 113, 113],
       [109, 109, 109, ..., 113, 113, 113],
       [109, 109, 109, ..., 113, 113, 113],
       ...,
       [ 30,  30,  30, ..., 109, 109, 109],
       [ 30,  30,  30, ..., 109, 109, 109],
       [ 30,  30,  30, ..., 109, 109, 109]], dtype=uint8)

In [79]:
hsvimg

array([[[ 40, 221,  98],
        [ 40, 221,  98],
        [ 40, 221,  97],
        ...,
        [ 42, 201,  94],
        [ 42, 199,  95],
        [ 42, 195,  97]],

       [[ 40, 231,  94],
        [ 40, 226,  96],
        [ 40, 221,  97],
        ...,
        [ 42, 207,  91],
        [ 42, 201,  94],
        [ 42, 195,  97]],

       [[ 40, 231,  94],
        [ 40, 226,  96],
        [ 40, 221,  97],
        ...,
        [ 42, 207,  91],
        [ 42, 199,  95],
        [ 42, 193,  98]],

       ...,

       [[ 42, 232,  99],
        [ 42, 232,  99],
        [ 42, 230, 100],
        ...,
        [ 42, 207, 100],
        [ 43, 217,  93],
        [ 43, 212,  95]],

       [[ 42, 232,  99],
        [ 42, 232,  99],
        [ 42, 232,  99],
        ...,
        [ 42, 209,  99],
        [ 43, 219,  92],
        [ 43, 212,  95]],

       [[ 42, 232,  99],
        [ 42, 234,  98],
        [ 42, 234,  98],
        ...,
        [ 42, 209,  99],
        [ 43, 221,  91],
        [ 43, 219,  92]]

In [ ]:
cv2.imshow('h',h)
cv2.imshow('s',s)
cv2.imshow('v',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
bim = bi(img)
cv2.imshow('biner',bim)
cv2.imshow('rgb',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
showImage(bim)

In [33]:
bim

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [7]:
def rgb_to_hsv2(r, g, b):
    r, g, b = r/255.0, g/255.0, b/255.0
    mx = max(r, g, b)
    mn = min(r, g, b)
    df = mx-mn
    if mx == mn:
        h = 0
    elif mx == r:
        h = (60 * ((g-b)/df) + 360) % 360
    elif mx == g:
        h = (60 * ((b-r)/df) + 120) % 360
    elif mx == b:
        h = (60 * ((r-g)/df) + 240) % 360
    if mx == 0:
        s = 0
    else:
        s = (df/mx)*100
    v = mx*100
    return h, s, v

In [10]:
edo = np.array([[[0,255,0],[0,243,0],[60,238,61],[72,206,76]],
       [[0,255,0],[18,253,0],[117,255,120],[144,250,151]]])

(0.3284552845528455, 0.8723404255319149, 0.9215686274509803)

In [9]:
rgb_to_hsv(edo)

array([[[120.        ,   1.        ,   1.        ],
        [120.        ,   1.        ,   1.        ],
        [119.66292135,   0.74789916,   0.66295265],
        [118.20895522,   0.65048544,   0.5819209 ]],

       [[120.        ,   1.        ,   1.        ],
        [124.2687747 ,   1.        ,   0.93357934],
        [118.69565217,   0.54117647,   0.51829268],
        [116.03773585,   0.424     ,   0.4587156 ]]])

In [16]:
max(72,206,76)

206

In [75]:
= edo[0,0,0]

0

In [34]:
# Python program to print 
# mode of elements 
from collections import Counter 
  
# list of elements to calculate mode 
n_num = [1, 2, 3, 4, 5, 5] 
n = len(n_num) 
  
data = Counter(n_num) 
get_mode = dict(data) 
mode = [k for k, v in get_mode.items() if v == max(list(data.values()))] 
  
if len(mode) == n: 
    get_mode = "No mode found"
else: 
    get_mode = "Mode is / are: " + ', '.join(map(str, mode)) 
      
print(get_mode) 

Mode is / are: 5


In [35]:
data

Counter({1: 1, 2: 1, 3: 1, 4: 1, 5: 2})

In [36]:
dict(data)

{1: 1, 2: 1, 3: 1, 4: 1, 5: 2}

In [43]:
get_mode.items()

AttributeError: 'str' object has no attribute 'items'

In [19]:
max(2,3,1)

3