In [1]:
import numpy as np
import cv2
import math

# rgb = np.uint8([[[0,255,0 ]]])
# hsv = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)

def showImage(data):
    if(type(data) is list):
        for i in range(len(data)):
            cv2.imshow('Gambar'+str(i+1),data[i])
    elif((type(data).__module__) == "numpy"):
        cv2.imshow('Gambar',data)
    else:
        print('File Error')
    
    cv2.waitKey(0)
    cv2.destroyAllWindows() 

def draw(b,g,r):
    draw = np.zeros([500,500,3])
    draw[:,:,:1].fill(b)
    draw[:,:,1:2].fill(g)
    draw[:,:,2:3].fill(r)
    return draw

def truncate(f, n):
    return math.floor(f * 10 ** n) / 10 ** n

def bgr2hsv(img):
    (M, N, C) = img.shape
    newImage = np.zeros([M,N,C])
    for m in range(M):
        for n in range(N):

            Ba = img[m,n,0]/255
            Ga = img[m,n,1]/255
            Ra = img[m,n,2]/255
            
            cmax = max(Ra,Ga,Ba)
            cmin = min(Ra,Ga,Ba)
            delta = cmax-cmin

            if(delta==0):
                H = 0
            elif(cmax == Ra):
                H = 60*(((Ga-Ba)/delta) % 6)
            elif(cmax == Ga):
                H = 60*(((Ba-Ra)/delta)+ 2)
            elif(cmax == Ba):
                H = 60*(((Ra-Ga)/delta)+ 4)           
            
            if(cmax == 0):
                S = 0
            else:
                S = delta/cmax
                

            
            V = cmax
            
            newImage[m,n,0] = round(H) 
            newImage[m,n,1] = truncate(S,3)*100
            newImage[m,n,2] = truncate(V,3)*100
    return newImage

def bgr2hsv2(img):  
    (M, N, C) = img.shape
    newImage = np.zeros([M,N,C])
    for m in range(M):
        for n in range(N):
            B = float(img[m,n,0]) 
            G = float(img[m,n,1])
            R = float(img[m,n,2])

            V = max(R,G,B)

            Vm = V-min(R,G,B)

            if(V == 0):
                S = 0
            elif(V > 0):
                S = Vm/V

            if(S == 0):
                H = 0
            elif(V == R):
                H = (60/360)*(((G-B)/Vm)%6)
            elif(V == G):
                H = (60/360)*(2+((B-R)/Vm))
            elif(V == B):
                H = (60/360)*(4+((R-G)/Vm))

            if(H < 0):
                H = H(m,n)+360          

            newImage[m,n,0] = H 
            newImage[m,n,1] = S
            newImage[m,n,2] = V
    return newImage
# def hsv2bgr(img):
#     (M, N, C) = img.shape
#     newImage = np.zeros([M,N,C])
#     for m in range(M):
#         for n in range(N):
            
#             H = img[m,n,0] 
#             S = (img[m,n,1])
#             V = (img[m,n,2])
            
#             C = V * S

#             X = C * (1 - abs((H / 60) % 2 - 1))

#             m = V - C
            
#             if(H>=0 and H<60):
#                 (Ra,Ga,Ba) = (C,X,0)
#             elif(H>=60 and H<120):
#                 (Ra,Ga,Ba) = (X,C,0)
#             elif(H>=120 and H<180):
#                 (Ra,Ga,Ba) = (0,C,X)
#             elif(H>=180 and H<240):
#                 (Ra,Ga,Ba) = (0,X,C)
#             elif(H>=240 and H<300):
#                 (Ra,Ga,Ba) = (X,0,C)
#             elif(H>=300 and H<360):
#                 (Ra,Ga,Ba) = (C,0,X)
            
#             (R,G,B) = (((Ra+m)*255),((Ga+m)*255),((Ba+m)*255))
            
#             newImage[m,n,0] = B
#             newImage[m,n,1] = G
#             newImage[m,n,2] = R
            
#     return V

In [424]:
color = np.uint8([[[0,255,0 ]]])
hsv = cv2.cvtColor(color,cv2.COLOR_BGR2HSV)
rgb = cv2.cvtColor(hsv,cv2.COLOR_HSV2BGR)

In [2]:
showImage(draw(1,90,200))

In [439]:
cv2.cvtColor(np.uint8([[[255,0,225 ]]]),cv2.COLOR_BGR2HSV)

array([[[147, 255, 255]]], dtype=uint8)

In [417]:
csgreen

array([[[120., 100., 100.]]])

In [418]:
show

array([[[  0.33333333,   1.        , 255.        ]]])