In [17]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2).fit(X_train)
pca_2d = pca.transform(X_train)

NameError: name 'X_train' is not defined

In [6]:
a

array([[1],
       [3],
       [4]])

In [7]:
b

array([[1, 2, 3]])

In [8]:
np.dot(a,b)

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [9]:
np.dot(b,a)

array([[19]])

In [13]:
np.dot(b,a)

array([[19]])