In [206]:
import numpy as np
import math

In [207]:
#inisialisasi Array
x = np.array([[]])
y = np.array([[]])

In [213]:
#Insert Data
x = np.array([[]])
x = np.append(x,[[0.12754495, 0.27328262, 0.12516046, 0.09987776, 0.035886575, 0.032590449, 0.07260479, 0.11954675, 0.27328262]],axis = 1)
x = np.append(x,[[0.15088975, 0.026249984, 0.022723604, 0.014922906, 0.012968333, 0.044205263, 0.029304616, 0.032117538, 0.049614504]],axis = 0)
x = np.append(x,[[0.013878325, 0.019257149, 0.069052674, 0.044492051, 0.03945737, 0.031512253, 0.017326111, 0.004935669, 0.008482872]],axis = 0)
x = np.append(x,[[0.040298317, 0.030995749, 0.024047103, 0.018927943, 0.017341301, 0.025317641, 0.011101517, 0.028269431, 0.010242061]],axis = 0)
x = np.append(x,[[0.0971625, 0.26421747, 0.26515943, 0.18636486, 0.019709533, 0.007429486, 0.011253806, 0.013172934, 0.017112879]],axis = 0)


y = np.array([[]])
y = np.append(y,[[1]],axis = 1)
y = np.append(y,[[-1]],axis = 0)
y = np.append(y,[[-1]],axis = 0)
y = np.append(y,[[-1]],axis = 0)
y = np.append(y,[[-1]],axis = 0)

In [214]:
np.dot(x[0],x[1])

0.05218549601910416

In [215]:
# Perhitungan 𝐾(𝑥𝑖,𝑥)= 𝑥𝑖𝑇𝑥 
n = len(x)
xtx = np.zeros([n,n])
yty = np.zeros([n,n])
for i in range(n):
    for j in range(n):
        valx = np.dot(x[j],np.transpose(x[i]))
        valy = np.dot(y[j],np.transpose(y[i]))
        xtx[i][j] = valx
        yty[i][j] = valy

In [216]:
# Proses mendapatkan nilai ai diawali dengan mengubah setiap data training menjadi nilai vektor (support vector) = 𝑥𝑦
svx = []
svy = []
for i in range(n):
    valx = 0
    valy = 0
    for j in range(n):
        valx = valx + np.dot(x[j],np.transpose(x[i]))
        valy = valy + np.dot(y[j],np.transpose(y[i]))
    svx.append(valx) 
    svy.append(valy)
    
svx = np.array(svx)
svy = np.array(svy)

In [217]:
# Perhitungan Bias
bix = []
biy = []
for i in range(n):
    valx = 0
    valy = 0
    
    valx = 4 - svy[i] + abs(svx[i] - svy[i])
    valy = 4 - svx[i] + abs(svy[i] - svx[i])
    
    bix.append(valx) 
    biy.append(valy)

In [218]:
#Proses selanjutnya adalah mencari nilai ai, sebelum itu masing – masing 
#support vector akan diberi bias 1 untuk mendapatkan jarak tegak lurus optimal juga berguna untuk mendapatkan hyperplane.
b = np.zeros([len(bix),3])
for i in range(n):
    b[i][0] = bix[i]
    b[i][1] = biy[i]
    b[i][2] = 1

In [219]:
# mencari nilai ai seperti persamaan
ait = np.zeros([len(b),len(b)])
for i in range(len(b)):
    val = 0
    for j in range(len(b)):
        val = np.dot(np.array([b[j]]),np.array([b[i]]).transpose())
        ait[i][j] = val

In [220]:
# Perhitungan persamaan dengan Gauss Jordan
# a = np.linalg.solve(ait, biy)
a = [0,0,0,0,0]
a[0] = -1.318731449
a[1] = 13.375
a[2] = -38.1875
a[3] = 29.03125
a[4] = -2.0546875

In [221]:
test = []
for i in range(n):
    val = 0
    for j in range(n):
        val += (ait[i,j]*a[j])    
    test.append(val)

In [222]:
val = np.zeros([5,3])
result = np.zeros([3])
for i in range(n):
    val[i] = np.dot(a[i],b[i])
    

In [223]:
val

array([[ -13.79849686,   -9.23112014,   -1.31873145],
       [  51.70671221,   90.03842443,   13.375     ],
       [-149.51072826, -260.83395652,  -38.1875    ],
       [ 114.03438649,  199.03752297,   29.03125   ],
       [  -7.35577541,  -12.65686333,   -2.0546875 ]])

array([-4.92390184,  6.35400741,  0.84533105])

In [224]:
np.dot(a[0],b[0]) + np.dot(a[1],b[1]) + np.dot(a[2],b[2]) + np.dot(a[3],b[3]) + np.dot(a[4],b[4])

array([-4.92390184,  6.35400741,  0.84533105])

In [155]:
val = np.array([[]])
val = np.append(val,np.dot(a[0],b[0]))
np.append(val,np.dot(a[1],b[1]),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [152]:
val

array([-13.79849686,  -9.23112014,  -1.31873145])

In [78]:
b[2]

array([3.91517455, 6.83034911, 1.        ])

In [114]:
val[0][0] + val[1][0] + val[2][0] + val[3][0] + val[4][0]

3.0262827614629133

In [112]:
-1.318731449 + 13.375 -38.1875 +29.03125 -2.0546875

0.8453310510000023

In [116]:
(-1.318731449*10.46346235) + (13.375*3.865922409) + (-38.1875*3.915174554) +(29.03125*3.915174554) + (-2.0546875*3.915174554)

-5.984561872481841

In [110]:
a

[-1.318731449, 13.375, -38.1875, 29.03125, -2.0546875]

In [111]:
sum(a)

0.8453310510000023