In [85]:
import numpy as np
import math

In [315]:
#inisialisasi Data
x = []
x.append(np.array([[0.12754495, 0.27328262, 0.12516046, 0.09987776, 0.035886575, 0.032590449, 0.07260479, 0.11954675, 0.27328262]]))
x.append(np.array([[0.15088975, 0.026249984, 0.022723604, 0.014922906, 0.012968333, 0.044205263, 0.029304616, 0.032117538, 0.049614504]]))
x.append(np.array([[0.013878325, 0.019257149, 0.069052674, 0.044492051, 0.03945737, 0.031512253, 0.017326111, 0.004935669, 0.008482872]]))
x.append(np.array([[0.040298317, 0.030995749, 0.024047103, 0.018927943, 0.017341301, 0.025317641, 0.011101517, 0.028269431, 0.010242061]]))
x.append(np.array([[0.0971625, 0.26421747, 0.26515943, 0.18636486, 0.019709533, 0.007429486, 0.011253806, 0.013172934, 0.017112879]]))

y = []
y.append([[1]])
y.append([[-1]])
y.append([[-1]])
y.append([[-1]])
y.append([[-1]])

In [316]:
x

[array([[0.12754495, 0.27328262, 0.12516046, 0.09987776, 0.03588657,
         0.03259045, 0.07260479, 0.11954675, 0.27328262]]),
 array([[0.15088975, 0.02624998, 0.0227236 , 0.01492291, 0.01296833,
         0.04420526, 0.02930462, 0.03211754, 0.0496145 ]]),
 array([[0.01387833, 0.01925715, 0.06905267, 0.04449205, 0.03945737,
         0.03151225, 0.01732611, 0.00493567, 0.00848287]]),
 array([[0.04029832, 0.03099575, 0.0240471 , 0.01892794, 0.0173413 ,
         0.02531764, 0.01110152, 0.02826943, 0.01024206]]),
 array([[0.0971625 , 0.26421747, 0.26515943, 0.18636486, 0.01970953,
         0.00742949, 0.01125381, 0.01317293, 0.01711288]])]

In [306]:
# Perhitungan 𝐾(𝑥𝑖,𝑥)= 𝑥𝑖𝑇𝑥 
sx = len(x)
sy = len(y)
xtx = np.zeros([sx,sx])
yty = np.zeros([sy,sy])
for i in range(sx):
    for j in range(sx):
        valx = np.dot(x[j],np.transpose(x[i]))
        valy = np.dot(y[j],np.transpose(y[i]))
        xtx[i][j] = valx
        yty[i][j] = valy

In [321]:
# Proses mendapatkan nilai ai diawali dengan mengubah setiap data training menjadi nilai vektor (support vector) = 𝑥𝑦
svx = []
svy = []
for i in range(sx):
    valx = 0
    valy = 0
    for j in range(sx):
        valx = valx + np.dot(x[j],np.transpose(x[i]))
        valy = valy + np.dot(y[j],np.transpose(y[i]))
    svx.append(valx) 
    svy.append(valy)

In [322]:
svx

[array([[0.46346235]]),
 array([[0.13407759]]),
 array([[0.08482545]]),
 array([[0.07201252]]),
 array([[0.42000284]])]

In [319]:
bix = []
biy = []
for i in range(sx):
    valx = 0
    valy = 0
    
    valx = 4 - svy[i] + abs(svx[i] - svy[i])
    valy = 4 - svx[i] + abs(svy[i] - svx[i])
    
    bix.append(valx) 
    biy.append(valy)

In [320]:
bix

[array([[10.46346235]]),
 array([[3.86592241]]),
 array([[3.91517455]]),
 array([[3.92798748]]),
 array([[3.57999716]])]

In [94]:
a = np.zeros([len(bix),3])
for i in range(len(a)):
    a[i][0] = bix[i]
    a[i][1] = biy[i]
    a[i][2] = 1

In [95]:
ait = np.zeros([len(a),len(a)])
for i in range(len(a)):
    val = 0
    for j in range(len(a)):
        val = np.dot(np.array([a[i]]),np.array([a[j]]).transpose())
        ait[i][j] = val

In [323]:
ait

array([[159.4840443 ,  88.57384728,  89.77872527,  90.09217378,
         81.57912572],
       [ 88.57384728,  61.26309071,  62.11661127,  62.3386543 ,
         56.30811707],
       [ 89.77872527,  62.11661127,  62.98226071,  63.20745905,
         57.09122548],
       [ 90.09217378,  62.3386543 ,  63.20745905,  63.43347824,
         57.2949508 ],
       [ 81.57912572,  56.30811707,  57.09122548,  57.2949508 ,
         51.76190967]])

In [61]:
ai = []
ai.append(-0.077357940935783276382)
ai.append(2.2947223774418206107)
ai.append(-2.4198610401646064564)
ai.append(1.9754949454708662456)
ai.append(-1.7729979972446651147)

In [12]:
jumlah = float(0)
for i in range(len(ait)):
    jumlah = ait[0][i]*ai[i]

In [13]:
jumlah

-144.6396265137869

In [226]:
jumlah = 0
for i in range(len(ait)):
    
    print(ait[0][i])

159.48404429997294
88.57384728147235
89.77872527247715
90.09217378337152
81.57912571732439


In [174]:
np.array([a[0]]).transpose()

array([[10.46346235],
       [ 7.        ],
       [ 1.        ]])

In [64]:
biy

[array([[7.]]),
 array([[6.73184482]]),
 array([[6.83034911]]),
 array([[6.85597496]]),
 array([[6.15999432]])]

In [96]:
4 - svy[0] + abs(svx[0] - svy[0])

array([[10.46346235]])

In [97]:
4 - svx[0] + abs(svy[0] - svx[0])

array([[7.]])

In [42]:
np.dot(x1,np.transpose(x1)) + np.dot(x2,np.transpose(x1)) + np.dot(x3,np.transpose(x1)) + np.dot(x4,np.transpose(x1)) + np.dot(x5,np.transpose(x1))

array([[0.46346235]])

In [14]:
K = np.array([[2,6,-4]])
M = np.transpose(np.array([[4,8,1]]))

In [234]:
159.4840443*ai[0] + 88.57384728*ai[1] + 89.77872528*ai[2] + 90.09217378*ai[3] + 81.57912572*ai[4]

7.0

In [227]:
ait

array([[159.4840443 ,  88.57384728,  89.77872527,  90.09217378,
         81.57912572],
       [ 88.57384728,  61.26309071,  62.11661127,  62.3386543 ,
         56.30811707],
       [ 89.77872527,  62.11661127,  62.98226071,  63.20745905,
         57.09122548],
       [ 90.09217378,  62.3386543 ,  63.20745905,  63.43347824,
         57.2949508 ],
       [ 81.57912572,  56.30811707,  57.09122548,  57.2949508 ,
         51.76190967]])

In [14]:
def gauss(A):
    m = len(A)
    assert all([len(row) == m + 1 for row in A[1:]]), "Matrix rows have non-uniform length"
    n = m + 1
    
    for k in range(m):
        pivots = [abs(A[i][k]) for i in range(k, m)]
        i_max = pivots.index(max(pivots)) + k
        
        # Check for singular matrix
        assert A[i_max][k] != 0, "Matrix is singular!"
        
        # Swap rows
        A[k], A[i_max] = A[i_max], A[k]

        
        for i in range(k + 1, m):
            f = A[i][k] / A[k][k]
            for j in range(k + 1, n):
                A[i][j] -= A[k][j] * f

            # Fill lower triangular matrix with zeros:
            A[i][k] = 0
    
    # Solve equation Ax=b for an upper triangular matrix A         
    x = []
    for i in range(m - 1, -1, -1):
        x.insert(0, A[i][m] / A[i][i])
        for k in range(i - 1, -1, -1):
            A[k][m] -= A[k][i] * x[0]
    return x

In [41]:
gauss(mat)

AssertionError: Matrix is singular!

In [38]:
B = ait.shape[0]
K = ait.shape[0] + 1
mat = np.zeros([B,K])

In [39]:
for i in range(B):
    for j in range(K):
        if(j == (K-1)):
            mat[i,j] = biy[i]
        else:
            mat[i,j] = ait[i,j]


array([[7.]])

In [65]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(ait, biy)
a

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 1 is different from 5)

In [86]:
np.array([])

array([], dtype=float64)